// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL08KRI0v6uN4L-RExnB6Wx49Pd_GHPQ8',
    appId: '1:508324968825:web:7eafb7bf9874e1f12717a8',
    messagingSenderId: '508324968825',
    projectId: 'habitopia1-c2787',
    authDomain: 'habitopia1-c2787.firebaseapp.com',
    storageBucket: 'habitopia1-c2787.firebasestorage.app',
    measurementId: 'G-Y3DB29GHYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx3NR1ZjlFYsW1qH8CZCmmV-duh8vmzbc',
    appId: '1:508324968825:android:d6d77636aa350cba2717a8',
    messagingSenderId: '508324968825',
    projectId: 'habitopia1-c2787',
    storageBucket: 'habitopia1-c2787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_raun919eQwpNe6qCyW4BXbySEayLyl0',
    appId: '1:508324968825:ios:b3d5b43b19b9ed962717a8',
    messagingSenderId: '508324968825',
    projectId: 'habitopia1-c2787',
    storageBucket: 'habitopia1-c2787.firebasestorage.app',
    iosBundleId: 'com.example.habitopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_raun919eQwpNe6qCyW4BXbySEayLyl0',
    appId: '1:508324968825:ios:b3d5b43b19b9ed962717a8',
    messagingSenderId: '508324968825',
    projectId: 'habitopia1-c2787',
    storageBucket: 'habitopia1-c2787.firebasestorage.app',
    iosBundleId: 'com.example.habitopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL08KRI0v6uN4L-RExnB6Wx49Pd_GHPQ8',
    appId: '1:508324968825:web:2dab650b5ebf9acb2717a8',
    messagingSenderId: '508324968825',
    projectId: 'habitopia1-c2787',
    authDomain: 'habitopia1-c2787.firebaseapp.com',
    storageBucket: 'habitopia1-c2787.firebasestorage.app',
    measurementId: 'G-9CQT2WNZN1',
  );
}
